name: OWASP Lite (Semgrep + Gitleaks)

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  gitleaks:  # ------------------- Secrets Scanning (A08) -------------------
    name: Secrets scan (A08)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          # Fail the job if any secrets are found
          args: detect --no-git -v

  semgrep:   # ------------------- SAST OWASP Top 10 ------------------------
    name: SAST OWASP Top 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This action runs Semgrep and WRITES a SARIF file we can upload.
      - name: Run Semgrep (OWASP Top 10)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          sarif: semgrep.sarif

      - name: Upload Semgrep SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
